##! Loads scripts that are auto-generated by ZeekControl and may contain
##! options that override the settings of the distribution's node
##! configuration or even the user's local.zeek configuration.
@load local-networks
@load zeekctl-config
