#! /usr/bin/env bash
#
# Broctl test setup script used with the tests in broctl/testing/btest/*.
# This script should be run at the start of each test to cleanup and
# install the necessary files for each test.
# Usage:  broctl-test-setup <broctl.cfg> <networks.cfg> <node.cfg>

if [ -z "${INSTALL}" ]; then
    echo "Error: INSTALL not defined in btest.cfg" > /dev/stderr
    exit 1
fi

tarfile=${INSTALL}.tar

if [ ! -f "$tarfile" ]; then
    echo "Error: $tarfile doesn't exist ('make buildbro' to create)" > /dev/stderr
    exit 1
fi

# Create test-specific bro installation
basedir=`dirname "${INSTALL}"`
newprefix="$basedir"/test.$$
mkdir "$newprefix"
(cd "$newprefix" && tar xf "$tarfile")

# install test-specific files
cp "${BROCTLCFG}/$1" "$newprefix/etc/broctl.cfg"
cp "${BROCTLCFG}/$2" "$newprefix/etc/networks.cfg"
cp "${BROCTLCFG}/$3" "$newprefix/etc/node.cfg"

echo $newprefix
