#! /usr/bin/env python
#
# Convert large integers in the to-bytes.awk output to floating point
# exponential format, because some versions of awk output large integers in
# that format.

import sys

for line in sys.stdin:
    outstr = ""
    for field in line.split():
        try:
            num = float(field)
        except ValueError:
            num = 0

        if num > 2147483647:
            outstr += "%.5e " % num
        else:
            outstr += "%s " % field

    print outstr[:-1]
