#! /usr/bin/env python3
#
# Convert large integers in the to-bytes.awk output to floating point
# exponential format, because some versions of awk output large integers in
# that format.

from __future__ import print_function
import sys

bignumber = 2**31-1

for line in sys.stdin:
    outstr = ""
    for field in line.split():
        try:
            num = float(field)
        except ValueError:
            num = 0

        if num > bignumber:
            outstr += "%.5e " % num
        else:
            outstr += "%s " % field

    print(outstr[:-1])
