#! /usr/bin/env bash
#
# Replace columns from broctl cron's stats.log
# that are not predictable with Xs.

awk '{ 
    if ( $1 ~ /^[0-9]+\.[0-9]+$/ ) { $1 = "XXXXXXXXXX.XX" }
    if ( NF > 4 ) { $5 = "X" }

    print
}'
