#!/usr/bin/env bash
#
# Fake the ifconfig command output.
#
echo "\
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 55523  bytes 621508855 (592.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 55523  bytes 621508855 (592.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0"
