### BTest baseline data generated by btest-diff. Do not edit. Use "btest -U/-u" to update. Requires BTest >= 0.63.
# Begin code from af_packet plugin

@if( peer_description == "worker-1-1" ) 
  redef AF_Packet::block_size = 0;
  redef AF_Packet::block_timeout = 0;
  redef AF_Packet::buffer_size = 0;
  redef AF_Packet::checksum_validation_mode = CHECKSUM_OFF;
  redef AF_Packet::enable_defrag = T;
  redef AF_Packet::enable_fanout = T;
  redef AF_Packet::enable_hw_timestamping = T;
  redef AF_Packet::fanout_id = 123;
  redef AF_Packet::fanout_mode = AF_Packet::FANOUT_HASH;
  redef AF_Packet::link_type = 2;
@endif
# End code from af_packet plugin
