##! Loads scripts that are auto-generated by BroControl and may contain
##! options that override the settings of the distribution's node
##! configuration or even the user's local-<node>.bro configuration.
@load local-networks
@load broctl-config
